//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vsempoka
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч инф о заказе.
    /// </summary>
    // *** Start programmer edit section *** (ТЧИнфОЗаказе CustomAttributes)

    // *** End programmer edit section *** (ТЧИнфОЗаказе CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч инф о заказе")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧИнфОЗаказеE", new string[] {
            "Количество as \'Количество\'",
            "Клиенты as \'Клиенты\'",
            "Клиенты.НаимЗаказа as \'Наим заказа\'",
            "Товары as \'Товары\'",
            "Товары.НаимТовара as \'Наим товара\'"}, Hidden=new string[] {
            "Клиенты.НаимЗаказа",
            "Товары.НаимТовара"})]
    [MasterViewDefineAttribute("ТЧИнфОЗаказеE", "Клиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НаимЗаказа")]
    [MasterViewDefineAttribute("ТЧИнфОЗаказеE", "Товары", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НаимТовара")]
    public class ТЧИнфОЗаказе : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.Vsempoka.Клиенты fКлиенты;
        
        private IIS.Vsempoka.Товары fТовары;
        
        private IIS.Vsempoka.ДокумПоставки fДокумПоставки;
        
        // *** Start programmer edit section *** (ТЧИнфОЗаказе CustomMembers)

        // *** End programmer edit section *** (ТЧИнфОЗаказе CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ТЧИнфОЗаказе.Количество CustomAttributes)

        // *** End programmer edit section *** (ТЧИнфОЗаказе.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ТЧИнфОЗаказе.Количество Get start)

                // *** End programmer edit section *** (ТЧИнфОЗаказе.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ТЧИнфОЗаказе.Количество Get end)

                // *** End programmer edit section *** (ТЧИнфОЗаказе.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧИнфОЗаказе.Количество Set start)

                // *** End programmer edit section *** (ТЧИнфОЗаказе.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ТЧИнфОЗаказе.Количество Set end)

                // *** End programmer edit section *** (ТЧИнфОЗаказе.Количество Set end)
            }
        }
        
        /// <summary>
        /// Т ч инф о заказе.
        /// </summary>
        // *** Start programmer edit section *** (ТЧИнфОЗаказе.Клиенты CustomAttributes)

        // *** End programmer edit section *** (ТЧИнфОЗаказе.Клиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Vsempoka.Клиенты Клиенты
        {
            get
            {
                // *** Start programmer edit section *** (ТЧИнфОЗаказе.Клиенты Get start)

                // *** End programmer edit section *** (ТЧИнфОЗаказе.Клиенты Get start)
                IIS.Vsempoka.Клиенты result = this.fКлиенты;
                // *** Start programmer edit section *** (ТЧИнфОЗаказе.Клиенты Get end)

                // *** End programmer edit section *** (ТЧИнфОЗаказе.Клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧИнфОЗаказе.Клиенты Set start)

                // *** End programmer edit section *** (ТЧИнфОЗаказе.Клиенты Set start)
                this.fКлиенты = value;
                // *** Start programmer edit section *** (ТЧИнфОЗаказе.Клиенты Set end)

                // *** End programmer edit section *** (ТЧИнфОЗаказе.Клиенты Set end)
            }
        }
        
        /// <summary>
        /// Т ч инф о заказе.
        /// </summary>
        // *** Start programmer edit section *** (ТЧИнфОЗаказе.Товары CustomAttributes)

        // *** End programmer edit section *** (ТЧИнфОЗаказе.Товары CustomAttributes)
        [PropertyStorage(new string[] {
                "Товары"})]
        [NotNull()]
        public virtual IIS.Vsempoka.Товары Товары
        {
            get
            {
                // *** Start programmer edit section *** (ТЧИнфОЗаказе.Товары Get start)

                // *** End programmer edit section *** (ТЧИнфОЗаказе.Товары Get start)
                IIS.Vsempoka.Товары result = this.fТовары;
                // *** Start programmer edit section *** (ТЧИнфОЗаказе.Товары Get end)

                // *** End programmer edit section *** (ТЧИнфОЗаказе.Товары Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧИнфОЗаказе.Товары Set start)

                // *** End programmer edit section *** (ТЧИнфОЗаказе.Товары Set start)
                this.fТовары = value;
                // *** Start programmer edit section *** (ТЧИнфОЗаказе.Товары Set end)

                // *** End programmer edit section *** (ТЧИнфОЗаказе.Товары Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Vsempoka.ДокумПоставки.
        /// </summary>
        // *** Start programmer edit section *** (ТЧИнфОЗаказе.ДокумПоставки CustomAttributes)

        // *** End programmer edit section *** (ТЧИнфОЗаказе.ДокумПоставки CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ДокумПоставки"})]
        public virtual IIS.Vsempoka.ДокумПоставки ДокумПоставки
        {
            get
            {
                // *** Start programmer edit section *** (ТЧИнфОЗаказе.ДокумПоставки Get start)

                // *** End programmer edit section *** (ТЧИнфОЗаказе.ДокумПоставки Get start)
                IIS.Vsempoka.ДокумПоставки result = this.fДокумПоставки;
                // *** Start programmer edit section *** (ТЧИнфОЗаказе.ДокумПоставки Get end)

                // *** End programmer edit section *** (ТЧИнфОЗаказе.ДокумПоставки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧИнфОЗаказе.ДокумПоставки Set start)

                // *** End programmer edit section *** (ТЧИнфОЗаказе.ДокумПоставки Set start)
                this.fДокумПоставки = value;
                // *** Start programmer edit section *** (ТЧИнфОЗаказе.ДокумПоставки Set end)

                // *** End programmer edit section *** (ТЧИнфОЗаказе.ДокумПоставки Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧИнфОЗаказеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧИнфОЗаказеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧИнфОЗаказеE", typeof(IIS.Vsempoka.ТЧИнфОЗаказе));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧИнфОЗаказе.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧИнфОЗаказе CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧИнфОЗаказе CustomAttributes)
    public class DetailArrayOfТЧИнфОЗаказе : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Vsempoka.DetailArrayOfТЧИнфОЗаказе members)

        // *** End programmer edit section *** (IIS.Vsempoka.DetailArrayOfТЧИнфОЗаказе members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧИнфОЗаказе by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧИнфОЗаказе.
        /// </summary>
        public DetailArrayOfТЧИнфОЗаказе(IIS.Vsempoka.ДокумПоставки fДокумПоставки) : 
                base(typeof(ТЧИнфОЗаказе), ((ICSSoft.STORMNET.DataObject)(fДокумПоставки)))
        {
        }
        
        public IIS.Vsempoka.ТЧИнфОЗаказе this[int index]
        {
            get
            {
                return ((IIS.Vsempoka.ТЧИнфОЗаказе)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Vsempoka.ТЧИнфОЗаказе dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
