//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vsempoka
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Формир распред.
    /// </summary>
    // *** Start programmer edit section *** (ФормирРаспред CustomAttributes)

    // *** End programmer edit section *** (ФормирРаспред CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФормирРаспредE", new string[] {
            "НомерРаспред as \'Номер распред\'",
            "Дата as \'Дата\'",
            "ДокумПоставки as \'Докум поставки\'",
            "ДокумПоставки.Дата as \'Дата\'",
            "ПунктПогруз as \'Пункт погруз\'",
            "ПунктПогруз.Наим as \'Наим\'",
            "СписокКонтей as \'Список контей\'",
            "СписокКонтей.НаимКонтей as \'Наим контей\'",
            "СписокБарж as \'Список барж\'",
            "СписокБарж.Производитель as \'Производитель\'"}, Hidden=new string[] {
            "ДокумПоставки.Дата",
            "ПунктПогруз.Наим",
            "СписокКонтей.НаимКонтей",
            "СписокБарж.Производитель"})]
    [MasterViewDefineAttribute("ФормирРаспредE", "ДокумПоставки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Дата")]
    [MasterViewDefineAttribute("ФормирРаспредE", "ПунктПогруз", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наим")]
    [MasterViewDefineAttribute("ФормирРаспредE", "СписокКонтей", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НаимКонтей")]
    [MasterViewDefineAttribute("ФормирРаспредE", "СписокБарж", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Производитель")]
    [View("ФормирРаспредL", new string[] {
            "НомерРаспред as \'Номер распред\'",
            "Дата as \'Дата\'",
            "ДокумПоставки.Дата as \'Дата\'",
            "ПунктПогруз.Наим as \'Наим\'",
            "СписокКонтей.НаимКонтей as \'Наим контей\'",
            "СписокБарж.Производитель as \'Производитель\'"})]
    public class ФормирРаспред : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерРаспред;
        
        private System.DateTime fДата;
        
        private IIS.Vsempoka.ДокумПоставки fДокумПоставки;
        
        private IIS.Vsempoka.ПунктПогруз fПунктПогруз;
        
        private IIS.Vsempoka.СписокКонтей fСписокКонтей;
        
        private IIS.Vsempoka.СписокБарж fСписокБарж;
        
        // *** Start programmer edit section *** (ФормирРаспред CustomMembers)

        // *** End programmer edit section *** (ФормирРаспред CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспред.Дата CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспред.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспред.Дата Get start)

                // *** End programmer edit section *** (ФормирРаспред.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ФормирРаспред.Дата Get end)

                // *** End programmer edit section *** (ФормирРаспред.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспред.Дата Set start)

                // *** End programmer edit section *** (ФормирРаспред.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ФормирРаспред.Дата Set end)

                // *** End programmer edit section *** (ФормирРаспред.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерРаспред.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспред.НомерРаспред CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспред.НомерРаспред CustomAttributes)
        public virtual int НомерРаспред
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспред.НомерРаспред Get start)

                // *** End programmer edit section *** (ФормирРаспред.НомерРаспред Get start)
                int result = this.fНомерРаспред;
                // *** Start programmer edit section *** (ФормирРаспред.НомерРаспред Get end)

                // *** End programmer edit section *** (ФормирРаспред.НомерРаспред Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспред.НомерРаспред Set start)

                // *** End programmer edit section *** (ФормирРаспред.НомерРаспред Set start)
                this.fНомерРаспред = value;
                // *** Start programmer edit section *** (ФормирРаспред.НомерРаспред Set end)

                // *** End programmer edit section *** (ФормирРаспред.НомерРаспред Set end)
            }
        }
        
        /// <summary>
        /// Формир распред.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспред.ДокумПоставки CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспред.ДокумПоставки CustomAttributes)
        [PropertyStorage(new string[] {
                "ДокумПоставки"})]
        [NotNull()]
        public virtual IIS.Vsempoka.ДокумПоставки ДокумПоставки
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспред.ДокумПоставки Get start)

                // *** End programmer edit section *** (ФормирРаспред.ДокумПоставки Get start)
                IIS.Vsempoka.ДокумПоставки result = this.fДокумПоставки;
                // *** Start programmer edit section *** (ФормирРаспред.ДокумПоставки Get end)

                // *** End programmer edit section *** (ФормирРаспред.ДокумПоставки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспред.ДокумПоставки Set start)

                // *** End programmer edit section *** (ФормирРаспред.ДокумПоставки Set start)
                this.fДокумПоставки = value;
                // *** Start programmer edit section *** (ФормирРаспред.ДокумПоставки Set end)

                // *** End programmer edit section *** (ФормирРаспред.ДокумПоставки Set end)
            }
        }
        
        /// <summary>
        /// Формир распред.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспред.ПунктПогруз CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспред.ПунктПогруз CustomAttributes)
        [PropertyStorage(new string[] {
                "ПунктПогруз"})]
        [NotNull()]
        public virtual IIS.Vsempoka.ПунктПогруз ПунктПогруз
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспред.ПунктПогруз Get start)

                // *** End programmer edit section *** (ФормирРаспред.ПунктПогруз Get start)
                IIS.Vsempoka.ПунктПогруз result = this.fПунктПогруз;
                // *** Start programmer edit section *** (ФормирРаспред.ПунктПогруз Get end)

                // *** End programmer edit section *** (ФормирРаспред.ПунктПогруз Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспред.ПунктПогруз Set start)

                // *** End programmer edit section *** (ФормирРаспред.ПунктПогруз Set start)
                this.fПунктПогруз = value;
                // *** Start programmer edit section *** (ФормирРаспред.ПунктПогруз Set end)

                // *** End programmer edit section *** (ФормирРаспред.ПунктПогруз Set end)
            }
        }
        
        /// <summary>
        /// Формир распред.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспред.СписокБарж CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспред.СписокБарж CustomAttributes)
        [PropertyStorage(new string[] {
                "СписокБарж"})]
        [NotNull()]
        public virtual IIS.Vsempoka.СписокБарж СписокБарж
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспред.СписокБарж Get start)

                // *** End programmer edit section *** (ФормирРаспред.СписокБарж Get start)
                IIS.Vsempoka.СписокБарж result = this.fСписокБарж;
                // *** Start programmer edit section *** (ФормирРаспред.СписокБарж Get end)

                // *** End programmer edit section *** (ФормирРаспред.СписокБарж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспред.СписокБарж Set start)

                // *** End programmer edit section *** (ФормирРаспред.СписокБарж Set start)
                this.fСписокБарж = value;
                // *** Start programmer edit section *** (ФормирРаспред.СписокБарж Set end)

                // *** End programmer edit section *** (ФормирРаспред.СписокБарж Set end)
            }
        }
        
        /// <summary>
        /// Формир распред.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспред.СписокКонтей CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспред.СписокКонтей CustomAttributes)
        [PropertyStorage(new string[] {
                "СписокКонтей"})]
        [NotNull()]
        public virtual IIS.Vsempoka.СписокКонтей СписокКонтей
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспред.СписокКонтей Get start)

                // *** End programmer edit section *** (ФормирРаспред.СписокКонтей Get start)
                IIS.Vsempoka.СписокКонтей result = this.fСписокКонтей;
                // *** Start programmer edit section *** (ФормирРаспред.СписокКонтей Get end)

                // *** End programmer edit section *** (ФормирРаспред.СписокКонтей Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспред.СписокКонтей Set start)

                // *** End programmer edit section *** (ФормирРаспред.СписокКонтей Set start)
                this.fСписокКонтей = value;
                // *** Start programmer edit section *** (ФормирРаспред.СписокКонтей Set end)

                // *** End programmer edit section *** (ФормирРаспред.СписокКонтей Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФормирРаспредE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормирРаспредE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормирРаспредE", typeof(IIS.Vsempoka.ФормирРаспред));
                }
            }
            
            /// <summary>
            /// "ФормирРаспредL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормирРаспредL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормирРаспредL", typeof(IIS.Vsempoka.ФормирРаспред));
                }
            }
        }
    }
}
